services:
  postgis:
    image: postgis/postgis:18-3.6
    container_name: subo-postgis
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "127.0.0.1:55432:5432"

    volumes:
      - postgis_data:/var/lib/postgresql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  otp:
    image: docker.io/opentripplanner/opentripplanner:2.9.0
    container_name: subo-otp
    restart: unless-stopped

    environment:
      JAVA_TOOL_OPTIONS: "-Xmx4g"
    ports:
      - "8081:8080"
    volumes:
      - ./otp/data:/var/opentripplanner
    command:
      - "--load"

volumes:
  postgis_data: